name: brick_breaker
description: "Re-implementing Woz's Breakout"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  flame_audio: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/